# Generated by Django 3.2.4 on 2021-06-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=70)),
                ('middlename', models.CharField(default='', max_length=70)),
                ('lastname', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=120)),
                ('department', models.CharField(default='', max_length=120)),
                ('authorities', models.CharField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('photoname', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
