# Generated by Django 3.2.4 on 2021-06-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_login',
            name='password',
            field=models.CharField(default='', help_text='8 digits', max_length=120),
        ),
        migrations.CreateModel(
            name='employment_hierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=70)),
                ('middlename', models.CharField(default='', max_length=70)),
                ('direct_report', models.CharField(default='', max_length=70)),
                ('department', models.CharField(default='', max_length=120)),
                ('eid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.employee_login')),
            ],
        ),
    ]
